config/routes.rb
Rails.application.routes.draw do
  root to: 'days#index'
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  resources  :users 
  resources  :cash_donors

  
  # devise_scope :user do
  #   delete 'sign_out', :to => 'devise/sessions#destroy', :as => :destroy_user_session
  # end
  #get 'days/active_day'      => 'days#active_day'
  get '/admin_dashboard'     => 'admin#admin_dashboard'
  #get 'days/show_unclaimed'  => 'days#show_unclaimed'
  
  
  resources :days do
    member do
      get '/active_day'          => 'days#active_day'
      get '/confirm_donation'    => 'days#confirm_donation'
      delete '/delete_reservation' => 'days#destroy'
    end
    collection do
      get '/claim_day'      => 'days#claim_day'
      get '/show_unclaimed' => 'days#show_unclaimed'
    end
  end
end

app/models/cash_donor.rb
class CashDonor < ActiveRecord::Base
end

app/models/day.rb
class Day < ActiveRecord::Base
    belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :omniauthable, :omniauth_providers => [:facebook, :twitter]
         
  has_many :days
  
  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.email = auth.info.email
      user.password = Devise.friendly_token[0,20]
      user.name = auth.info.name   # assuming the user model has a name
      # user.image = auth.info.image # assuming the user model has an image
    end
  end
  
  def self.new_with_session(params, session)
    super.tap do |user|
      if data = session["devise.facebook_data"] && session["devise.facebook_data"]["extra"]["raw_info"]
        user.email = data["email"] if user.email.blank?
      end
    end
  end
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  def admin_dashboard 
    if user_signed_in? 
      if !current_user.admin
          redirect_to root_path
      end
    else
      redirect_to root_path
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  
  before_filter :set_beginning_of_week
  
  private
  def set_beginning_of_week
    Date.beginning_of_week = :sunday
  end
end

app/controllers/cash_donors_controller.rb
class CashDonorsController < ApplicationController
  def show
    @cash_donor = CashDonor.find(params[:id])
  end

  def create
    @cash_donor = CashDonor.create(cash_donor_params)
    if @cash_donor.save
      redirect_to @cash_donor
    else
      flash[:alert] = 'Oops! Looks like that didn\'t work -- let\'s try again...'
      render 'new'
    end
  end

  def new
    @cash_donor             = CashDonor.new
    @cash_donor.day_claimed = params[:format] 
  end
  
  def edit
    @cash_donor = CashDonor.find(params[:id])
  end
  
  def update
    @cash_donor = CashDonor.find(params[:id])
    
    if @cash_donor.update_attributes(cash_donor_params)
      redirect_to @cash_donor
    else
      flash[:alert] = 'Oops! Looks like that didn\'t work -- let\'s try again...'
      render 'edit'
    end
  end
  
  def destroy
    @cash_donor = CashDonor.find(params[:id])
    @cash_donor.destroy
  
    redirect_to root_path
  end
  
  private
  def cash_donor_params
    params.require(:cash_donor).permit(:name, :email, :day_claimed, :donation_amount, :message)  
  end
end

app/controllers/days_controller.rb
class DaysController < ApplicationController
  def index
    @claimed_days = Day.all
  end
  
  def show
    @claimed_day  = Day.find(params[:id])
  end
  
  def show_unclaimed
    @date = params[:format]
  end
  
  def active_day
    @claimed_day = Day.find(params[:id])
  end
  
  def create
    # logger.debug(claimed_day_params)
    @claimed_day = Day.new(claimed_day_params)
    @claimed_day.user_id = current_user.id
    
    if @claimed_day.save
      redirect_to @claimed_day
    else
      flash[:alert] = 'Oops! Looks like that didn\'t work -- let\'s try again...'
      render 'new'
    end
  end
  
  def new
    @claimed_day       = Day.new
    @claimed_day.date  = params[:format]
  end
  
  # def claim_day
  #   @claimed_day         = Day.new
  #   @claimed_day.user_id = current_user.id
  #   @claimed_day.date    = params[:format]
    
  #   if @claimed_day.save
  #     redirect_to root_path
  #   end
  # end
  
  def confirm_donation
    @day = Day.find(params[:id])
    @day.donation_confirmed = true
    @day.save
    
    redirect_to admin_dashboard_path
  end
  
  def destroy
    @day = Day.find(params[:id])
    @day.destroy
  
    redirect_to root_path
  end
  
  private
  def claimed_day_params
    params.require(:day).permit(:name, :date, :donation_amount, :message)
    # params.require(:claimed_day).permit(:name, :date, :donation_amount, :message)  
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook
    # You need to implement the method below in your model (e.g. app/models/user.rb)
    @user = User.from_omniauth(request.env["omniauth.auth"])

    if @user.persisted?
      sign_in_and_redirect @user, :event => :authentication #this will throw if @user is not activated
      set_flash_message(:notice, :success, :kind => "Facebook") if is_navigational_format?
    else
      session["devise.facebook_data"] = request.env["omniauth.auth"]
      redirect_to new_user_registration_url
    end
  end
  
  def twitter
    @user = User.from_omniauth(request.env["omniauth.auth"])
    
    # Since Twitter doesn't give emails, create fake (but unique) email of twitter_username@twitter.com
    username = request.env['omniauth.auth']['extra']['raw_info']['screen_name']
    @user.email = username + '@twitter.com'
    
    
    if @user.save && @user.persisted?
      puts "SUCCESSSUCCESSSUCCESSSUCCESSSUCCESSSUCCESSSUCCESSSUCCESSSUCCESSSUCCESSSUCCESSSUCCESSSUCCESS"
      sign_in_and_redirect @user, :event => :authentication # This will throw if @user is not activated
      set_flash_message(:notice, :success, :kind => "Twitter") if is_navigational_format?
    else
      puts "FAILUREFAILUREFAILUREFAILUREFAILUREFAILUREFAILUREFAILUREFAILUREFAILUREFAILUREFAILUREFAILURE"
      # session["devise.twitter_data"] = request.env["omniauth.auth"].except("extra")
      redirect_to new_user_registration_url
    end
  end

  def failure
    redirect_to root_path
  end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!

  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
    unless @user == current_user
      redirect_to :back, :alert => "Access denied."
    end
  end

end

app/controllers/visitors_controller.rb
class VisitorsController < ApplicationController
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cash_donors_helper.rb
module CashDonorsHelper
end

app/helpers/day_helper.rb
module DayHelper
end

app/helpers/omniauth_callbacks_helper.rb
module OmniauthCallbacksHelper
end

app/views/admin/admin_dashboard.html.erb
<div class="container-fluid admin-dashboard">
    <h1>Admin Dashboard</h1>
    <% unconfirmed_days = Day.where(donation_confirmed: false) %>
    <% confirmed_days = Day.where(donation_confirmed: true) %>
    
    <div class="row">
        <div class="col-xs-0 col-md-2"></div>
        <div class="col-xs-12 col-md-3">
            <% unconfirmed_days.each do |unconfirmed_day| %>
                <p>
                   Donor: <%= unconfirmed_day.name %>, <br />
                   Email: <%= unconfirmed_day.user.email %>, <br />
                   Date reserved: <%= unconfirmed_day.date %> <br /> 
                   <%= link_to 'CONFIRM', confirm_donation_day_path(unconfirmed_day), :class => "confirm" %>
                       
                    OR 
                                
                   <%= link_to 'DELETE', delete_reservation_day_path(unconfirmed_day), method: :delete, data: { confirm: 'Are you sure about this?' }, :class => "destroy" %>
                </p>
                <hr />
            <% end %>
        </div>
        <div class="col-xs-0 col-md-2"></div>
        <div class="col-xs-12 col-md-3">
            <% confirmed_days.each do |confirmed_day| %>
                <p>Payment for <%= confirmed_day.date %> has been confirmed</p>
            <% end %>
        </div>
        <div class="col-xs-0 col-md-2"></div>
    </div>
</div>

app/views/cash_donors/edit.html.erb
<h2>EDIT</h2>
<%= form_for @cash_donor do |f| %>
    <div class="form-group">
        <%= f.label      :name, class: "label-text" %>
        <%= f.text_field :name, class: "form-control", required: true %>
    </div>
    
    <div class="form-group">
        <%= f.label      :email, class: "label-text" %>
        <%= f.text_field :email, class: "form-control", required: true %>
    </div>
    
    <div class="form-group">
        <%= f.label :day_claimed, class: "label-text"%>
        <%= f.text_field  :day_claimed, class: "form-control", required: true %>
    </div>
    
    <div class="form-group">
        <%= f.label   :donation_amount, class: "label-text" %>
        <%= f.text_field :donation_amount, class: "form-control", required: true %>
    </div>
    
    <div class="form-group">
        <%= f.label     :message, class: "label-text" %>
        <%= f.text_area :message, class: "form-control", required: false %>
    </div>
    
    <div class="actions">
        <%= f.submit 'Submit', class: "btn btn-large btn-primary" %>
    </div>
<% end %>

app/views/cash_donors/new.html.erb
<h2>TEST</h2>
<%= form_for @cash_donor do |f| %>
    <div class="form-group">
        <%= f.label      :name, class: "label-text" %>
        <%= f.text_field :name, class: "form-control", required: true %>
    </div>
    
    <div class="form-group">
        <%= f.label      :email, class: "label-text" %>
        <%= f.text_field :email, class: "form-control", required: true %>
    </div>
    
    <div class="form-group">
        <%= f.label :day_claimed, class: "label-text"%>
        <%= f.text_field  :day_claimed, class: "form-control", required: true %>
    </div>
    
    <div class="form-group">
        <%= f.label   :donation_amount, class: "label-text" %>
        <%= f.text_field :donation_amount, class: "form-control", required: true %>
    </div>
    
    <div class="form-group">
        <%= f.label     :message, class: "label-text" %>
        <%= f.text_area :message, class: "form-control", required: false %>
    </div>
    
    <div class="actions">
        <%= f.submit 'Submit', class: "btn btn-large btn-primary" %>
    </div>
<% end %>

app/views/cash_donors/show.html.erb
<div class="show-cash-donor">
    <div class="container-fluid">
        <h1><%= @cash_donor.day_claimed.strftime("%B %d, %Y") %></h1>
        <h3>Claimed by <%= @cash_donor.name %></h3>
        <p class="message">From <%= @cash_donor.name %>: "<%= @cash_donor.message %>"</p>
        
        <div class="nav-back">
            <p><%= link_to 'Back to calendar', days_path %></p>
            <% if user_signed_in? && current_user.admin? %>
                <p><%= link_to 'Edit This Cash Donor\'s Info', edit_cash_donor_path(@cash_donor) %></p>

                <p><%= link_to 'Delete', @cash_donor, method: :delete, data: { confirm: 'Are you sure about this?' } %></p>
            <% end %>
        </div>
    </div>
</div>

app/views/days/active_day.html.erb
<!-- This is the day-page that will be called from the calendar -->
<!-- It will stand in for days whether they exist as objects or not -->
<% # render 'days/day_logic' %>

<h1><%= @cash_donor.name %></h1>
<h2><%= @cash_donor.day_claimed %></h2>
<p><%= link_to 'Back to calendar', days_path %></p>

app/views/days/index.html.erb
<div class="orb-calendar">
    <%= month_calendar do |date| %>
      <%= date %>
    <% end %>
</div>
<!--<div id='donation'></div>-->

app/views/days/new.html.erb
<h2>Claim This Day</h2>
<%= form_for @claimed_day do |f| %>
    <div class="form-group">
        <%= f.label      :name, class: "label-text" %>
        <%= f.text_field :name, class: "form-control", required: true %>
    </div>
    
    <div class="form-group">
        <%= f.label       :date, class: "label-text"%>
        <%= f.text_field  :date, class: "form-control", required: true %>
    </div>
    
    <div class="form-group">
        <%= f.label      :donation_amount, class: "label-text" %>
        <%= f.text_field :donation_amount, class: "form-control", required: true %>
    </div>
    
    <div class="form-group">
        <%= f.label     :message, class: "label-text" %>
        <%= f.text_area :message, class: "form-control", required: false %>
    </div>
    
    <div class="actions">
        <%= f.submit 'Continue To Payment', class: "btn btn-large btn-primary" %>
    </div>
<% end %>

app/views/days/show.html.erb
<div class="show-day">
    <div class="container-fluid">
        <h1><%= @claimed_day.date.strftime("%B %d, %Y") %></h1>
        <h3>Claimed by <%= @claimed_day.name %></h3>
        <p class="message">From <%= @claimed_day.name %>: "<%= @claimed_day.message %>"</p>
        
        <% if user_signed_in? %>
            <% if current_user.id === @claimed_day.user_id && @claimed_day.donation_confirmed == false %>
                <div class="widget-container">
                    <p>Please complete your donation using the Fractured Atlas payment system below. Your date claim will be reserved as pending until Orbiter 3 receives receipt of your donation.</p>
                    <a href="https://www.fracturedatlas.org/site/fiscal/profile?id=11285" class="donate-link" target="_blank">DONATE HERE</a>
                    <p>(Thank you for donating! This message will dissappear once Orbiter 3 has confirmed your payment.)</p>
                </div>
            <% end %>
        <% end %>
        
        <div class="nav-back">
            <p><%= link_to 'Back to calendar', days_path %></p>
            <% if user_signed_in? && current_user.admin? %>
                <p><%= link_to 'Delete', @claimed_day,
                                       method: :delete,
                                       data: { confirm: 'Are you sure about this?' } %></p>
            <% end %>
        </div>
    </div>
    <% if user_signed_in? %>
         <!--<p>current user: <%= current_user.id %> / claimed user: <%= @claimed_day.user_id %></p> -->
    <% end %>
</div>

app/views/days/show_unclaimed.html.erb
<h2><%= @date %> has not been claimed yet!</h2>
<% if user_signed_in? %>
    <p>Click here to <%= link_to 'claim this day', new_day_path(@date) %>.</p> <!-- new_day_path claim_day_days_path -->
    <% if current_user.admin? %>
        <p>Click here to <%= link_to 'add a cash donor', new_cash_donor_path(@date) %></p>
    <% end %>
<% else %>
    <p>Please <%= link_to 'sign in', new_user_registration_path %> to claim this day</p>
<% end %>

app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Bootstrap 3.0 %>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name.to_s == 'notice' ? 'success' : 'danger' %>">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_mobile_nav.html.erb
<nav class="orb-nav mobile-content navbar navbar-default">
	<ul class="nav navbar navbar-nav">
		<li class="col-xs-6"><%= link_to image_tag("orbiter-3-logo.png", alt: "Orbiter3 Logo", width: "164px", class: "orbiter-3-logo"),
        'http://www.orbiter3.org/' %></li>
        <li class="col-xs-3"></li>
		<li class="nav-click mob-nav col-xs-3"><%= link_to image_tag("mobile-nav.svg", alt: "Mobile Nav Icon")%></li>
	</ul>
</nav>

app/views/layouts/_nav_links_for_auth.html.erb
<% if user_signed_in? %>
  <li><%= link_to 'Edit account', edit_user_registration_path %></li>
  <li><%= link_to 'Sign out', destroy_user_session_path, :method=>'delete' %></li>
<% else %>
  <li><%= link_to 'Sign in', new_user_session_path %></li>
  <li><%= link_to 'Sign up', new_user_registration_path %></li>
<% end %>

app/views/layouts/_navigation.html.erb
<%# navigation styled for Bootstrap 3.0 %>
<nav class="orb-nav hidden-nav">
	<div class="container-fluid">
		<ul class="nav navbar-nav" id="nav-center">
		  <%= render 'layouts/navigation_links' %>
		</ul>
	</div>
</nav>
<nav class="orb-nav failsafe-nav">
	<div class="container">
		<ul class="nav nav-justified" id="nav-center">
		  <%= render 'layouts/navigation_links' %>
		</ul>
	</div>
</nav>

app/views/layouts/_navigation_links.html.erb
<%# add navigation links to this file %>
<% if user_signed_in? %>
    <li><%= link_to 'Sign-Out', destroy_user_session_path, method: 'delete' %></li>
    <% if current_user.admin? %>
        <li><%= link_to 'Admin', admin_dashboard_path %></li>
    <% end %>
<% else %>
    <li><%= link_to 'Sign-In', new_user_session_path %></li>
<% end %>
<li><%= link_to 'Calendar', root_path %></li>
<li class="orbiter-3-logo"><%= link_to image_tag("orbiter-3-logo.png", alt: "Orbiter3 Logo", width: "164px", class: "orbiter-3-logo"),
            'http://www.orbiter3.org/' %></li>
<li><a href="http://www.orbiter3.org/how-it-works">How It Works</a></li>
<li><a href="http://www.orbiter3.org/contact-calendar-app">Contact</a></li>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Orbiter3 Calendar" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Orbiter3 Calendar" %>">
    
    <link href='https://fonts.googleapis.com/css?family=Roboto' rel='stylesheet' type='text/css'>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <header>
      <%= render 'layouts/mobile_nav' %>
      <%= render 'layouts/navigation' %>
    </header>
    <main role="main">
       <%= render 'layouts/messages' %>
       <%= yield %>
    </main>
  </body>
</html>

app/views/pages/about.html.erb
<% content_for :title do %>About<% end %>
<h3>About the Website</h3>
<p>
This web application was created with
<%= link_to('Rails Composer', 'http://railsapps.github.io/rails-composer/') %>
from the <%= link_to('RailsApps project', 'http://railsapps.github.io/') %>.
</p>

app/views/simple_calendar/_month_calendar(div_containers).html.erb
<div class="simple-calendar">
  <%= link_to "Previous", start_date: date_range.first - 1.day  %>
  <%= I18n.t("date.month_names")[start_date.month] %> <%= start_date.year %>
  <%= link_to "Next", start_date: date_range.last + 1.day  %>

  <div class="container-fluid">
    <div class="row">
        <% date_range.slice(0, 7).each do |day| %>
          <div class="col-sm-1">
            <h3><%= I18n.t("date.abbr_day_names")[day.wday] %></h3>
          </div>
        <% end %>
    </div>

    <div class="container">
      <% date_range.each_slice(7) do |week| %>
        <tr>
          <% week.each do |day| %>
            <%= content_tag :td, class: calendar.td_classes_for(day) do %>
              <!-- this is where we put things for each day -->
              <% claimed_day = Day.find_by_date(day) %>
              <% cash_donor  = CashDonor.find_by_day_claimed(day)%>
              
              <% # Cash donor  %>
              <% if cash_donor %>
               <p>Claimed by: <%= cash_donor.name %></p>
               
               <% # Link to Day view for cash donor %>
               <p><%= link_to 'View day for cash donor', cash_donor_path(cash_donor) %></p>
              
              <% # Regular user %>
              <% elsif claimed_day %>
                <p>Claimed by: <%= claimed_day.user.email %></p>
                
                <% # Link to Day view for regular user %>
                <p><%= link_to 'View day for regular user', day_path(claimed_day) %></p>
                
                <% if user_signed_in? && claimed_day.user == current_user %>
                  <% tweeted_day = day.strftime('%a, %d %b, %Y')  %>
                  <a href="https://twitter.com/share" class="twitter-share-button" data-url="http://google.com" data-text="Yo! The Button works. Do not press. <%= tweeted_day %>" data-via="syzygygerund" data-size="large" data-hashtags="thisisthetest">Tweet</a>
  <script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0],p=/^http:/.test(d.location)?'http':'https';if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src=p+'://platform.twitter.com/widgets.js';fjs.parentNode.insertBefore(js,fjs);}}(document, 'script', 'twitter-wjs');</script>
                <% end %>
              <% else %>
              
                <% # No view at the moment for unclaimed day %>
                <% if user_signed_in? %>
                    <p><%= link_to 'View Day', show_unclaimed_days_path(day) %></p>
                <% end %>            
              <% end %>
              <% if defined?(Haml) && block_is_haml?(block) %>
                <% capture_haml do %>
                  <% block.call day, sorted_events.fetch(day, []) %>
                <% end %>
              <% else %>
                <% block.call day, sorted_events.fetch(day, []) %>
              <% end %>
            <% end %>
          <% end %>
        </tr>
      <% end %>
    </div>
  </div>
</div>

app/views/simple_calendar/_month_calendar(original).html.erb
<div class="simple-calendar">
  <%= link_to "Previous", start_date: date_range.first - 1.day  %>
  <%= I18n.t("date.month_names")[start_date.month] %> <%= start_date.year %>
  <%= link_to "Next", start_date: date_range.last + 1.day  %>

  <table class="table table-striped">
    <thead>
      <tr>
        <% date_range.slice(0, 7).each do |day| %>
          <th><%= I18n.t("date.abbr_day_names")[day.wday] %></th>
        <% end %>
      </tr>
    </thead>

    <tbody>
      <% date_range.each_slice(7) do |week| %>
        <tr>
          <% week.each do |day| %>
            <%= content_tag :td, class: calendar.td_classes_for(day) do %>
              <!-- this is where we put things for each day -->
              <% claimed_day = Day.find_by_date(day) %>
              <% cash_donor  = CashDonor.find_by_day_claimed(day)%>
              
              <% # Cash donor  %>
              <% if cash_donor %>
               <p>Claimed by: <%= cash_donor.name %></p>
               
               <% # Link to Day view for cash donor %>
               <p><%= link_to 'View day for cash donor', cash_donor_path(cash_donor) %></p>
              
              <% # Regular user %>
              <% elsif claimed_day %>
                <p>Claimed by: <%= claimed_day.user.email %></p>
                
                <% # Link to Day view for regular user %>
                <p><%= link_to 'View day for regular user', day_path(claimed_day) %></p>
                
                <% if user_signed_in? && claimed_day.user == current_user %>
                  <% tweeted_day = day.strftime('%a, %d %b, %Y')  %>
                  <a href="https://twitter.com/share" class="twitter-share-button" data-url="http://google.com" data-text="Yo! The Button works. Do not press. <%= tweeted_day %>" data-via="syzygygerund" data-size="large" data-hashtags="thisisthetest">Tweet</a>
  <script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0],p=/^http:/.test(d.location)?'http':'https';if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src=p+'://platform.twitter.com/widgets.js';fjs.parentNode.insertBefore(js,fjs);}}(document, 'script', 'twitter-wjs');</script>
                <% end %>
              <% else %>
              
                <% # No view at the moment for unclaimed day %>
                <% if user_signed_in? %>
                    <p><%= link_to 'View Day', show_unclaimed_days_path(day) %></p>
                <% end %>            
              <% end %>
              <% if defined?(Haml) && block_is_haml?(block) %>
                <% capture_haml do %>
                  <% block.call day, sorted_events.fetch(day, []) %>
                <% end %>
              <% else %>
                <% block.call day, sorted_events.fetch(day, []) %>
              <% end %>
            <% end %>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/simple_calendar/_month_calendar.html.erb
<div class="simple-calendar">
  <div id="month-nav" style="text-align: center;">
    <h1>the oCal</h2>
    <ul style="padding: 0;">
      <li class="previous-month" style="display: inline;"><%= link_to "<", start_date: date_range.first - 1.day %></li>
      <li style="display: inline;" id="current-month"><%= I18n.t("date.abbr_month_names")[start_date.month] %> <%= start_date.year %></li>
      <li class="next-month" style="display: inline;"><%= link_to ">", start_date: date_range.last + 1.day %></li>
    </ul>

    <h3 class="match-donor"></h3>
    <% if user_signed_in? == false %>
      <h4>Please sign in above in order to use the calendar</h4>
    <% end %>
  </div>
  
  <script type="text/javascript">
      setCurrentMonth();
      setMatchDonor();
  </script>
  
  <div class="container-fluid">
    <div class="cal-row"> 
      <% date_range.slice(0, 7).each do |day| %>
        <div class="weekdays">
          <h4><%= I18n.t("date.abbr_day_names")[day.wday] %></h4>
        </div>
      <% end %>
    </div> 

    <% date_range.each_slice(7) do |week| %>
      <div class="cal-row">
        <% week.each do |day| %>
          <%= content_tag :div, class: [calendar.td_classes_for(day)] do %>
            <!-- this is where we put things for each day -->
            <p class="day-date-raw"><% block.call day, sorted_events.fetch(day, []) %></p>
            <script type="text/javascript">
                // setDayDate();
                // setDayHeight();
                // blockApril();
            </script>
            
            <% claimed_day = Day.find_by_date(day) %>
            <% cash_donor  = CashDonor.find_by_day_claimed(day)%>
            
            <% # Cash donor  %>
            <% if cash_donor %>
              <% # Link to Day view for cash donor %>
              <p class="claimed-info"><%= link_to 'View Day', cash_donor_path(cash_donor) %></p>
              <div class="claimed-trigger"></div>
              <script type="text/javascript">
                addClaimedClass();
              </script>
              
            <% # Regular user %>
            <% elsif claimed_day %>
              <% # Link to Day view for regular user %>
              <p class="claimed-info"><%= link_to 'VIEW', day_path(claimed_day) %></p>
              
              <div class="claimed-trigger"></div>
              <script type="text/javascript">
                addClaimedClass();
              </script>
            <% else %>
            
              <% # Link to Unclaimed Day view for regular user %>
              <% if user_signed_in? %>
                <p id="unclaimed-link"><%= link_to 'CLAIM', show_unclaimed_days_path(day) %></p>
                 
              <% end %>            
            <% end %>
            <p class="day-date-output"></p>
          <% end %>
          <script type="text/javascript">
                setDayDate();
                setDayHeight();
                blockApril();
          </script>
        <% end %>
      </div>
    <% end %>
  </div>
</div>

<script type="text/javascript">
    clickClaimed();
</script>

app/views/visitors/index.html.erb
<h3>Welcome</h3>
<p><%= link_to 'Users:', users_path %> <%= User.count %> registered</p>